/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return application health status for monitoring and load balancers.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tickets Endpoint
         * @description List tickets with optional filters and pagination.
         *
         *     Returns:
         *         TicketListResponse: Paginated list of tickets with metadata.
         */
        get: operations["list_tickets_endpoint_api_v1_tickets_get"];
        put?: never;
        /**
         * Create Ticket Endpoint
         * @description Create a new ticket.
         *
         *     Raises:
         *         HTTPException(400) if service_id not found: FK constraint violation.
         *         HTTPException(400) if business rules violated.
         */
        post: operations["create_ticket_endpoint_api_v1_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ticket Endpoint
         * @description Get ticket by ID.
         *
         *     Raises:
         *         HTTPException(404) if ticket not found.
         */
        get: operations["get_ticket_endpoint_api_v1_tickets__ticket_id__get"];
        /**
         * Update Ticket Endpoint
         * @description Update ticket by ID. Accepts partial updates.
         *
         *     Raises:
         *         HTTPException(404) if ticket not found.
         *         HTTPException(400) if business rules violated.
         */
        put: operations["update_ticket_endpoint_api_v1_tickets__ticket_id__put"];
        post?: never;
        /**
         * Delete Ticket Endpoint
         * @description Delete ticket by ID.
         *
         *     Raises:
         *         HTTPException(404) if ticket not found.
         */
        delete: operations["delete_ticket_endpoint_api_v1_tickets__ticket_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Services Endpoint
         * @description List services.
         *
         *     Returns:
         *         list[Services]
         */
        get: operations["list_services_endpoint_api_v1_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents Endpoint
         * @description List documents with optional filters and pagination.
         *
         *     Return:
         *         DocumentListResponse: Paginated list of documents with metadata.
         */
        get: operations["list_documents_endpoint_api_v1_documents_get"];
        put?: never;
        /**
         * Create Document Endpoint
         * @description Create a new document.
         *
         *     Raises:
         *         HTTPException (400) if service_id not found: FK constraint violation.
         */
        post: operations["create_document_endpoint_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Endpoint
         * @description Get document by ID.
         *
         *     Raises:
         *         HTTPException (404) if document not found.
         */
        get: operations["get_document_endpoint_api_v1_documents__document_id__get"];
        /**
         * Update Document Endpoint
         * @description Update document by ID. Accepts partial updates.
         *
         *     Raises:
         *         HTTPException (404) if document not found.
         *         HTTPException (400) if service_id not found (FK violation)
         */
        put: operations["update_document_endpoint_api_v1_documents__document_id__put"];
        post?: never;
        /**
         * Delete Document Endpoint
         * @description Delete document by ID.
         *
         *     Raises:
         *         HTTPException (404) if document not found.
         */
        delete: operations["delete_document_endpoint_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Endpoint
         * @description Search document chunks using keyword, vector, or hybrid similarity.
         */
        get: operations["search_endpoint_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Endpoint
         * @description Handle chat.
         *
         *     Non-streaming (stream=false): returns ChatResponse JSON.
         *     Streaming (stream=true): returns text/event-stream with SSE events:
         *         - data: {"type": "token", "content": "..."} — each token
         *         - data: {"type": "done", "conversation_id": "...", "message_id": "...", "sources": [...], "route_used": "...", "confidence": ...} — after persistence
         *         - data: {"type": "error", "message": "..."} — on failure
         *
         *     Raises:
         *         HTTPException(404) if conversation not found (non-streaming only).
         */
        post: operations["chat_endpoint_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatOptions
         * @description Schema for configuration of response options.
         */
        ChatOptions: {
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /**
             * Include Sources
             * @default true
             */
            include_sources: boolean;
        };
        /**
         * ChatRequest
         * @description Request schema for chat.
         */
        ChatRequest: {
            /** Message */
            message: string;
            /** Conversation Id */
            conversation_id?: string | null;
            options?: components["schemas"]["ChatOptions"];
            /**
             * Stream
             * @default false
             */
            stream: boolean;
        };
        /**
         * ChatResponse
         * @description Response schema for chat.
         */
        ChatResponse: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["SourceItem"][];
            /**
             * Route Used
             * @enum {string}
             */
            route_used: "sql" | "hybrid" | "clarify";
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * DocType
         * @description Document types.
         * @enum {string}
         */
        DocType: "runbook" | "policy" | "guide" | "faq";
        /**
         * DocumentCreate
         * @description Request schema for creating a new document.
         *
         *     User provides: title, content, doc_type, service_id (optional).
         *     Database auto-generates: id, created_at.
         *     Background service later generates: chunks + embeddings.
         */
        DocumentCreate: {
            /**
             * Service Id
             * @description UUID of the IT-service this document related to
             * @example null
             */
            service_id?: string | null;
            /**
             * Title
             * @description Document title
             */
            title: string;
            /**
             * Content
             * @description Content of the document
             */
            content: string;
            /**
             * @description Document type
             * @example runbook
             * @example policy
             * @example guide
             * @example faq
             */
            doc_type: components["schemas"]["DocType"];
        };
        /**
         * DocumentDetailResponse
         * @description Response schema for full document details.
         *
         *     Includes the full 'content' field.
         *     Used for single document retrieval.
         */
        DocumentDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Service Id */
            service_id: string | null;
            /** Title */
            title: string;
            /** Content */
            content: string;
            doc_type: components["schemas"]["DocType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * DocumentListResponse
         * @description Response schema for paginated document list.
         */
        DocumentListResponse: {
            /** Items */
            items: components["schemas"]["DocumentResponse"][];
            /**
             * Total
             * @description Total number of documents matching filters
             */
            total: number;
            /**
             * Limit
             * @description Maximum items per page
             */
            limit: number;
            /**
             * Offset
             * @description Number of items skipped
             */
            offset: number;
        };
        /**
         * DocumentResponse
         * @description Response schema for document metadata.
         *
         *     Excludes 'content' field for performance.
         *     Used in document list.
         */
        DocumentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Service Id */
            service_id: string | null;
            /** Title */
            title: string;
            doc_type: components["schemas"]["DocType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * DocumentUpdate
         * @description Request schema for updating a existing document.
         *
         *     User provides: title, content, doc_type, service_id (all fields optional).
         *     Database auto-generates: updated_at.
         *     Background service later generates (if content is updated): chunks + embeddings.
         */
        DocumentUpdate: {
            /**
             * Service Id
             * @description UUID of the IT-service this document related to
             * @example null
             */
            service_id?: string | null;
            /**
             * Title
             * @description Document title
             */
            title?: string | null;
            /**
             * Content
             * @description Content of the document
             */
            content?: string | null;
            /**
             * @description Document type
             * @example runbook
             * @example policy
             * @example guide
             * @example faq
             */
            doc_type?: components["schemas"]["DocType"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Method
         * @description Enum for method query parameter.
         * @enum {string}
         */
        Method: "keyword" | "vector" | "hybrid";
        /**
         * SearchResponse
         * @description Response schema for top-level representation of chunk list.
         *
         *     Includes items, query, total, method.
         */
        SearchResponse: {
            /** Items */
            items: components["schemas"]["SearchResultItem"][];
            /** Query */
            query: string;
            /** Total */
            total: number;
            method: components["schemas"]["Method"];
        };
        /**
         * SearchResultItem
         * @description Response schema for detailed representation of one matching chunk.
         *
         *     Includes chunk_id, document_id, document_title, content, chunk_index, score.
         */
        SearchResultItem: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Content */
            content: string;
            /** Chunk Index */
            chunk_index: number;
            /** Score */
            score: number;
        };
        /**
         * ServiceResponse
         * @description Response schema for a single service.
         */
        ServiceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SourceItem
         * @description Schema for detailed representation of one matching source.
         */
        SourceItem: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Chunk Index */
            chunk_index: number;
            /** Relevance Score */
            relevance_score: number;
        };
        /**
         * TicketCreate
         * @description Request schema for creating a new ticket.
         */
        TicketCreate: {
            /**
             * Service Id
             * Format: uuid
             * @description UUID of the service this ticket belongs to
             */
            service_id: string;
            /**
             * Title
             * @description Ticket title
             */
            title: string;
            /**
             * Description
             * @description Detailed description of the issue
             */
            description?: string | null;
            /**
             * @description Priority level
             * @example p1
             * @example p2
             * @example p3
             * @example p4
             */
            priority: components["schemas"]["TicketPriority"];
            /**
             * Assignee
             * @description Assigned user
             */
            assignee?: string | null;
            /**
             * Reporter
             * @description User who reported the issue
             */
            reporter?: string | null;
        };
        /**
         * TicketListResponse
         * @description Response schema for paginated ticket list.
         */
        TicketListResponse: {
            /** Items */
            items: components["schemas"]["TicketResponse"][];
            /**
             * Total
             * @description Total number of tickets matching filters
             */
            total: number;
            /**
             * Limit
             * @description Maximum items per page
             */
            limit: number;
            /**
             * Offset
             * @description Number of items skipped
             */
            offset: number;
        };
        /**
         * TicketPriority
         * @description Ticket priority levels with SLA implications.
         * @enum {string}
         */
        TicketPriority: "p1" | "p2" | "p3" | "p4";
        /**
         * TicketResponse
         * @description Response schema for a single ticket.
         */
        TicketResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Assignee */
            assignee: string | null;
            /** Reporter */
            reporter: string | null;
        };
        /**
         * TicketStatus
         * @description Valid ticket statuses.
         * @enum {string}
         */
        TicketStatus: "open" | "in_progress" | "resolved" | "closed";
        /**
         * TicketUpdate
         * @description Request schema for updating an existing ticket.
         *
         *     All fields are optional to support partial updates.
         */
        TicketUpdate: {
            /**
             * Title
             * @description Ticket title
             */
            title?: string | null;
            /**
             * Description
             * @description Detailed description of the issue
             */
            description?: string | null;
            /**
             * @description Ticket status
             * @example open
             * @example in_progress
             * @example resolved
             * @example closed
             */
            status?: components["schemas"]["TicketStatus"] | null;
            /**
             * @description Priority level
             * @example p1
             * @example p2
             * @example p3
             * @example p4
             */
            priority?: components["schemas"]["TicketPriority"] | null;
            /**
             * Assignee
             * @description Assigned user
             */
            assignee?: string | null;
            /**
             * Reporter
             * @description User who reported the issue
             */
            reporter?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_tickets_endpoint_api_v1_tickets_get: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: components["schemas"]["TicketStatus"] | null;
                /** @description Filter by priority */
                priority?: components["schemas"]["TicketPriority"] | null;
                /** @description Filter by service ID */
                service_id?: string | null;
                /** @description Items per page */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket_endpoint_api_v1_tickets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_endpoint_api_v1_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ticket_endpoint_api_v1_tickets__ticket_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ticket_endpoint_api_v1_tickets__ticket_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_services_endpoint_api_v1_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"][];
                };
            };
        };
    };
    list_documents_endpoint_api_v1_documents_get: {
        parameters: {
            query?: {
                /** @description Filter by service ID */
                service_id?: string | null;
                /** @description Filter by document type */
                doc_type?: components["schemas"]["DocType"] | null;
                /** @description Search in document title (case-insensitive) */
                title_search?: string | null;
                /** @description Maximum number of documents to return */
                limit?: number;
                /** @description Number of documents to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_endpoint_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_endpoint_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_endpoint_api_v1_documents__document_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_endpoint_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_endpoint_api_v1_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /** @description Max amount of search results */
                limit?: number;
                /** @description Method query parameter */
                method?: components["schemas"]["Method"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_endpoint_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
