"""Add message_id column to QueryLog with FK.

Revision ID: 6d0a95e36f33
Revises: 86367b319221
Create Date: 2026-05-22 07:14:33.645421

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d0a95e36f33"
down_revision: str | Sequence[str] | None = "86367b319221"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query_logs", sa.Column("message_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_query_logs_message_id"), "query_logs", ["message_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_query_logs_message_id_messages"),
        "query_logs",
        "messages",
        ["message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_query_logs_message_id_messages"), "query_logs", type_="foreignkey")
    op.drop_index(op.f("ix_query_logs_message_id"), table_name="query_logs")
    op.drop_column("query_logs", "message_id")
    # ### end Alembic commands ###
