"""Add started_at and closed_at to tickets.

Revision ID: 86367b319221
Revises: 60c303fdc3e3
Create Date: 2026-03-02 19:05:17.615891

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86367b319221"
down_revision: str | Sequence[str] | None = "60c303fdc3e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tickets", sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "closed_at")
    op.drop_column("tickets", "started_at")
    # ### end Alembic commands ###
